export const CS3203 = {
    acadYear: '2020/2021',
    preclusion: 'CS3201, CS3202',
    description:
        'This module provides students with hands-on experience in\nworking in project groups through a complete SDLC to\ndevelop a well-designed, well-tested, large-scaled software\nsystem. The students will apply the current best software\nengineering practices on the analysis, design,\nimplementation, and testing of software system. Through\nthe project, students will practise analysis of user’s needs,\nformulation of computing requirements to meet the user’s\nneeds, modelling and design of the computer systems\naccording to the requirements, evaluation of the design,\nefficient implementation of software components, system\nintegration, software version control, and rigorous testing.',
    title: 'Software Engineering Project',
    department: 'Computer Science',
    faculty: 'Computing',
    workload: [2, 2, 0, 10, 6],
    prerequisite: '(CS2103/T or CS2113/T)',
    moduleCredit: '8',
    moduleCode: 'CS3203',
    attributes: { mpes1: true, mpes2: true },
    semesterData: [
        {
            semester: 1,
            timetable: [
                {
                    classNo: '1',
                    startTime: '1200',
                    endTime: '1400',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Lecture',
                    size: 160,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '1',
                    startTime: '1600',
                    endTime: '1800',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Lecture',
                    size: 160,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '01',
                    startTime: '1000',
                    endTime: '1200',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Recitation',
                    size: 90,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '02',
                    startTime: '1400',
                    endTime: '1600',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Recitation',
                    size: 90,
                    covidZone: 'Unknown',
                },
            ],
            covidZones: ['Unknown'],
        },
        {
            semester: 2,
            timetable: [
                {
                    classNo: '2',
                    startTime: '1400',
                    endTime: '1600',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Lecture',
                    size: 105,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '1',
                    startTime: '1400',
                    endTime: '1600',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Lecture',
                    size: 100,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '03',
                    startTime: '1000',
                    endTime: '1200',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Wednesday',
                    lessonType: 'Recitation',
                    size: 40,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '02',
                    startTime: '1600',
                    endTime: '1800',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Recitation',
                    size: 40,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '01',
                    startTime: '1200',
                    endTime: '1400',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Recitation',
                    size: 40,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '05',
                    startTime: '1400',
                    endTime: '1600',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Wednesday',
                    lessonType: 'Recitation',
                    size: 40,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '1',
                    startTime: '1000',
                    endTime: '1200',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Lecture',
                    size: 100,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '06',
                    startTime: '1600',
                    endTime: '1800',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Wednesday',
                    lessonType: 'Recitation',
                    size: 40,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '04',
                    startTime: '1200',
                    endTime: '1400',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Wednesday',
                    lessonType: 'Recitation',
                    size: 40,
                    covidZone: 'Unknown',
                },
                {
                    classNo: '2',
                    startTime: '1000',
                    endTime: '1200',
                    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    venue: 'E-Learn_C',
                    day: 'Tuesday',
                    lessonType: 'Lecture',
                    size: 105,
                    covidZone: 'Unknown',
                },
            ],
            covidZones: ['Unknown'],
        },
        { semester: 3, timetable: [], covidZones: [] },
    ],
    prereqTree: { or: ['CS2103', 'CS2103T', 'CS2113', 'CS2113T'] },
};

test('We need a test here', () => undefined);
