env:
  es6: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 2018
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  indent: off
  no-console: off
  no-fallthrough: off
  '@typescript-eslint/no-empty-function': off
  require-atomic-updates: off
  no-lonely-if: off
  arrow-body-style: off
  require-yield: off

  # temporary until migration is complete
  '@typescript-eslint/no-this-alias': off
  '@typescript-eslint/no-explicit-any': off

  # correctness checks
  strict:
    - error
    - global
  consistent-return: error
  array-callback-return: error
  eqeqeq:
    - error
    - always
  no-var: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    -
      varsIgnorePattern: _
      args: none
  no-shadow-restricted-names: error
  no-promise-executor-return: error
  no-case-declarations: warn
  no-eval: error
  no-proto: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: warn
  no-useless-call: warn
  no-useless-return: warn
  no-void: error
  no-self-compare: error
  prefer-promise-reject-errors: error
  no-label-var: error
  no-new-object: error
  no-invalid-this: error
  prefer-arrow-callback: warn
  prefer-numeric-literals: error
  no-constructor-return: error
  no-new-wrappers: error
  no-return-await: warn
  no-unused-expressions: warn

  # code style
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  curly:
    - error
    - multi-or-nest
    - consistent
  dot-location:
    - error
    - property
  arrow-parens:
    - error
    - always
  '@typescript-eslint/array-type':
    - error
    -
      default: array-simple
  block-spacing: error
  computed-property-spacing: error
  func-call-spacing: error
  keyword-spacing:
    - error
    -
      overrides:
        catch:
          before: true
          after: false
  space-before-function-paren:
    - error
    -
      anonymous: never
      named: never
      asyncArrow: always
  generator-star-spacing:
    - error
    -
      anonymous:
        before: false
        after: false
      named:
        before: false
        after: true
      method:
        before: false
        after: false
  '@typescript-eslint/type-annotation-spacing':
    - error
    -
      before: true
      after: true
